### ISSUE TITLE
React - memory leak when component unmount before response.

### ISSUE THREAD

**Issue by kvt** [krimlabs/eiphop#13]
I want to unsubscribe pending events on unmount react component because it is causing memory leak.
`Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.`

**Comment by anis-campos** [comment]
Hello @kvt, eiphop is not react-aware, and I would say, even electron isn't. AFAIK, IPC requests cannot be aborted, so if you are unmounting a component during a IPC requests, the only option you have to not call setState() is something like this:
```javascript
class News extends Component {
  _isMounted = false;

  constructor(props) {
    super(props);

    this.state = {
      news: [],
    };
  }

  componentDidMount() {
    this._isMounted = true;

    axios
      .get('https://hn.algolia.com/api/v1/search?query=react')
      .then(result => {
        if (this._isMounted) {
          this.setState({
            news: result.data.hits,
          });
        }
      });
  }

  componentWillUnmount() {
    this._isMounted = false;
  }

  render() {
    ...
  }
}
```
[look here for more informations](https://www.robinwieruch.de/react-warning-cant-call-setstate-on-an-unmounted-component/)

**Comment by kvt** [comment]
Thanks @anis-campos,  Used trashable-react library, which fixed the problem.

**Comment by anis-campos** [comment]
@kvt thanks for the info, [trashable-react](https://github.com/hjylewis/trashable-react) is a really good  solution for this issue, some result that my previous post, but way more seamless 😁

**Comment by shivekkhurana** [comment]
Let's keep this issue open to see if there are other ways to handle this. 

I personally like the explicit approach suggested by @anis-campos (t.y. for the response btw) but `trashable-react` also seems to be a good idea.

**Comment by shivekkhurana** [comment]
I'm closing this issue. Both `trashable-react` and `isMounted` can be used as a solution. `isMounted` flag is recommended since it's explicit.
