### ISSUE TITLE
Timeout issue

### ISSUE THREAD

**Issue by FadyQJ** [krimlabs/eiphop#15]
I noticed when an action takes some time I get an error:
```
WebSocket connection to 'ws://localhost:3000/sockjs-node/324/1puq2ekr/websocket' failed:
WebSocket is closed before the connection is established.
```
I receive the data no problem but I am getting this warning.

An example code I am using is the following:
```js
console.log("Start");
emit('sourceGet', params).then(res => {
  console.log("End");
  setState({
    mode: 0,
    ...res
  });
});
```
The console output is
Start
The error mentionned
End

in `SourceGet` if I remove the function that takes time, the error dissapears.
The function is a nodejs addon (c++ based) so it should not intervene with eiphop.

And thanks for such a great api

**Comment by shivekkhurana** [comment]
Hi @FadyQJ 

Electron's IPC (the library Eiphop depends) on has no concept of timeout. Eiphop keeps track of your `emit`s and resolves when the main process returns a result. It never times out. 

My guess is that the warning is thrown by some part of `sourceGet` and not Eiphop. However, I'll be happy to investigate if you can setup a sample repo. 

Thanks

**Comment by FadyQJ** [comment]
Thanks @shivekkhurana 
This is the second time I report an issue where the problem is from my end :D
The code is probably my node addon because when I remove it the error goes away.
I'll investigate the issue and if anything comes up regarding Eiphop I'll report back.
