### ISSUE TITLE
res.notify is not a function

### ISSUE THREAD

**Issue by fennik** [krimlabs/eiphop#24]
I am getting the error `[ERROR] TypeError: res.notify is not a function` when trying to invoke notify.

When I dump the contents of `res` all I get is `{ send: [Function: send], error: [Function: error] }`

node: v11.10.1
eiphop: ^1.0.12

```
emit('ping', {id: 123}, (msg) => {
            console.log(msg)
        })
            .then((res) => console.log(res)) // will log {msg: 'pong'}
            .catch((err) => console.log(err))

const actions = {
    ping: (req, res) => {
        const {payload} = req
        res.notify('Downloading file ${payload.id}')
        res.send({msg: 'pong'})
    },
}

```

**Comment by shivekkhurana** [comment]
Your version seems to be correct, but I'm not able to understand why the `notify` function is missing.

Did you check the source for `main.js` in node_modules folder ?

**Comment by fennik** [comment]
I think I have found it, looks like the package hasn't been built in the current version. 

I ran `yarn build` and it now works

```
src/main.js
const res = {
			notify: (message) => event.sender.send('asyncResponseNotify', requestId, message),
			send: (result) => event.sender.send('asyncResponse', requestId, result),
			error: (err) => event.sender.send('errorResponse', requestId, err)
		};
```

```
lib/main.js
var res = {
      send: function send(result) {
        return event.sender.send('asyncResponse', requestId, result);
      },
      error: function error(err) {
        return event.sender.send('errorResponse', requestId, err);
      }
    };
```

**Comment by fennik** [comment]
Will you build the package and commit it please?

**Comment by shivekkhurana** [comment]
Done. Updated readme. The latest version is `1.0.13`.
