### ISSUE TITLE
error with `TypeError: Cannot read property 'ipcRenderer' of undefined` when runing react app in example/renderer

### ISSUE THREAD

**Issue by FredyVia** [krimlabs/eiphop#40]
OS: `Ubuntu 20.04 LTS`
electron version: `v12.0.2`
![image](https://user-images.githubusercontent.com/43921304/114721853-e55beb00-9d6b-11eb-8a09-4ea5e07ead8a.png)

**Comment by shivekkhurana** [comment]
Hey, I'm sorry for the delayed response. I missed the notification for this issue. 

Is this still an issue or were you able to resolve it? If it's still relevant, are you sure that `window.electron` is valid?
